name: Claim Daily Reward

on:
  schedule:
    - cron: '0 21 * * *' # KST(UTC+9) 06:00
  workflow_dispatch:

jobs:
  claim-daily-reward:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Set up Python
      run: pip install --upgrade --force-reinstall git+https://github.com/thesadru/genshin.py@dev

    - name: Claim daily reward
      env:
        HOYO_ACCOUNT_NUM: ${{ secrets.HOYO_ACCOUNT_NUM }}
        USERS_LTUID: ${{ secrets.USERS_LTUID }}
        USERS_LTOKEN: ${{ secrets.USERS_LTOKEN }}
        USERS_LTMID: ${{ secrets.USERS_LTMID }}
        USERS_TARGET_GAMES: ${{ secrets.USERS_TARGET_GAMES }}
      run: python claim_daily_reward.py
